### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by surajpunemaha** [DenisovAV/deep_links_flutter#9]
I/flutter ( 6794): The following MissingPluginException was thrown while activating platform stream on channel
I/flutter ( 6794): https.mydomain.com/events:
I/flutter ( 6794): MissingPluginException(No implementation found for method listen on channel
I/flutter ( 6794): https.mydomain.com/events)
I/flutter ( 6794): 
I/flutter ( 6794): When the exception was thrown, this was the stack:
I/flutter ( 6794): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
I/flutter ( 6794): <asynchronous suspension>
I/flutter ( 6794): #1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:545:9)
I/flutter ( 6794): <asynchronous suspension>
I/flutter ( 6794): ...

**Comment by surveshoeb** [comment]
Hi @surajpunemaha verify your channel value in `MainActivity.kt` and `main.dart` both files should have the same value
